### ISSUE TITLE
Forward SOCKS to HTTP proxy

### ISSUE THREAD

**Issue by mkhahani** [ravn/jsocks#1]
Hello,

I'm looking for a SOCKS server that can forward connections to a HTTP proxy server just like what Dante does. Can jsocks do that? If no, how much is that complicated to add such feature to jsocks?

Thanks.

**Comment by elbegemot** [comment]
I believe JSocks can do this with code tweak: reply correctly to connect and bind socks requests from client but instead of establishing connection to port and ip provided by socks client as regular socks proxy does - establish connection to fixed host:port of http proxy (effectively forwarding traffic to http proxy).

For this you can look into SocksProxyBase.onConnect, SocksProxyBase.startSession and Socks5Proxy.startSession methods and maybe some other places where standard java Socket class is created for outbound proxy server connections.

**Comment by mkhahani** [comment]
Thanks for the tips. I need this as part of my Android application. I'll appreciate if you help me this happen since I'm not familiar with JSocks and definitely you will do that better than me. I even can pay for it and I'm okay with the licence if you prefer that be part of your project.

Let me know if you can help, mkhahani-at-gmail

**Comment by ravn** [comment]
JSocks is just a plain Java program, which should respect the system properties telling it to go through a given proxy for outbound connections.  I have not tested it, but it is worth a try.  See http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html

**Comment by mkhahani** [comment]
@ravn No application can use proxy except it is aware of that and has required codes to support connecting through proxy.

@elbegemot I just discovered that JSocks can be chained to another SOCKS server and I could get it to work. So I'm trying to add support for chaining to HTTP proxy. I don't believe changing destination ip/port to ip/port of the proxy server is enough and I think I have to do more. At the moment, the HTTP header of the request that proxy server receives is empty! Any thought?

And even if it works, it will not work for SSL connections(https) and if I'm not mistaken I have to use HTTP `CONNECT` method to handle SSL connections.

I wonder there must be someone who has done this before but I can't find any codes for this.

**Comment by elbegemot** [comment]
I believe without extra configuration chained http proxy will be treated by JSocks as socks proxy with expected socks protocol responses that original http proxy can't satisfy.

**Comment by ravn** [comment]
The two types of proxy are not interchangeable, and glue code is needed.  I do not think that your approach will work.  You may consider setting the system properties on the _JSocks_ JVM so all external communication from JSocks will go through the http proxy.  If that will not work, I think you should consider another solution.

**Comment by mkhahani** [comment]
Actually the idea of changing connection ip/port worked! but not enough. I had to parse the HTTP request header and convert relative URI to absolute by concatenating `Host`. It works for non-encrypted connections only. For an encrypted connection(e.g. SSL) as I said before you need to send a HTTP `CONNECT` request to proxy server and after the connection established, it works like a usual connection.

Thank you @elbegemot for the idea and you @ravn.

**Comment by chrisstone07** [comment]
@mkhahani i would like to know if you have achieved forwarding socks proxy to Http proxy, if so could you please mail me the details at chrischris_4425@hotmail.com,
also @elbegemot would you be available to make the changes for me?

Regards
George

**Comment by ravn** [comment]
Grown stale.
